### ISSUE TITLE
启动后输入测试命令最后提示‘cookie为空 跳出X’

### ISSUE THREAD

**Issue by heweihao** [Darkatse/xmly-speed-docker#1]
cookie在github actions可以运行
是我哪里配置错了吗

**Comment by heweihao** [comment]
![image](https://user-images.githubusercontent.com/22342816/99327584-35b24800-28b5-11eb-9556-d326567062b4.png)

**Comment by Darkatse** [comment]
cookies用英文双引号括起来试试
