### ISSUE TITLE
群晖docker运行报错

### ISSUE THREAD

**Issue by notget** [Darkatse/xmly-speed-docker#2]
小白求助
通过群晖docker，从注册表中下载了xmly-speed-docker，双击映像创建容器，然后在高级设置中"环境"项增加一个XMLY_SPEED_COOKIE，填入手机抓取的cookie。运行后报错并容器停止运行。请帮忙看看谢谢！
![设置](https://user-images.githubusercontent.com/70825055/99542342-e8d18d00-29ec-11eb-9cc5-9c1354bad59a.png)
![日志](https://user-images.githubusercontent.com/70825055/99542355-ed964100-29ec-11eb-9c35-e7c9c4f93738.png)

**Comment by notget** [comment]
在github上正常跑的账号（cookie没变），在docker中启动跑完就容器停止。
![错误](https://user-images.githubusercontent.com/70825055/99543457-28e53f80-29ee-11eb-95bd-3dd5fd07c397.png)

**Comment by Darkatse** [comment]
群晖上的docker套件自带docker-compose，建议使用README.md内的教程进行安装
 xmly-speed-docker是我另一个仓库编译出的镜像，目前暂时还未更新
