### ISSUE TITLE
N1装不了

### ISSUE THREAD

**Issue by gogogogood** [Darkatse/xmly-speed-docker#3]
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

**Comment by Darkatse** [comment]
N1需要用arm的docker，请手动修改Dockerfile，把第一行FROM ubuntu:20.04换成FROM arm64v8/ubuntu:20.04
由于我没试过用arm构建，不清楚是否可以，之后会做出更新

**Comment by gogogogood** [comment]
好像是我网络的问题，卡住了。chinnkarahoi的京东可以装

**Comment by Darkatse** [comment]
> 好像是我网络的问题，卡住了。chinnkarahoi 的京东可以装

那这样的话理论上这个也可以，原理是一样的
