### ISSUE TITLE
这个不支持在OpenWRT下面的docker-compose

### ISSUE THREAD

**Issue by Nothend** [Darkatse/xmly-speed-docker#5]
看上去你的代码不支持在openwrt环境里面，因为apt命令在openwrt中无法使用，有解决办法吗，多谢了！openwrt中已经成功安装docker-compose

**Comment by Darkatse** [comment]
与是否支持apt无关，docker是独立环境，理论上只要有docker和docker-compose就能运行

**Comment by Nothend** [comment]
> 与是否支持apt无关，docker是独立环境，理论上只要有docker和docker-compose就能运行

多谢拨冗指教，一开始我也是这么想的，可是openwrt 下compose 其他的docker 可以安装，但是本项目，安装docker 的时候，先是警告apt 用法不是稳定的接口，我换成了apt-get警告消失。但是始终提示无法从“mirrors.163.com”fatch ，更改了阿里的源也是同样的错误

**Comment by Nothend** [comment]
> 与是否支持apt无关，docker是独立环境，理论上只要有docker和docker-compose就能运行

这里是错误提示信息：
Step 5/9 : RUN date && apt-get update && apt-get install -y cron openssl coreutils git wget tzdata          && apt-get update && apt-get install -y python3 python3-pip
 ---> Running in 303bc5d5ad48
Thu Feb 18 01:45:51 UTC 2021
Err:1 http://mirrors.163.com/ubuntu focal InRelease
  Temporary failure resolving 'mirrors.163.com'
Err:2 http://mirrors.163.com/ubuntu focal-updates InRelease
  Temporary failure resolving 'mirrors.163.com'
Err:3 http://mirrors.163.com/ubuntu focal-backports InRelease
  Temporary failure resolving 'mirrors.163.com'
Err:4 http://mirrors.163.com/ubuntu focal-security InRelease
  Temporary failure resolving 'mirrors.163.com'
Reading package lists...
W: Failed to fetch http://mirrors.163.com/ubuntu/dists/focal/InRelease  Temporary failure resolving 'mirrors.163.com'
W: Failed to fetch http://mirrors.163.com/ubuntu/dists/focal-updates/InRelease  Temporary failure resolving 'mirrors.163.com'
W: Failed to fetch http://mirrors.163.com/ubuntu/dists/focal-backports/InRelease  Temporary failure resolving 'mirrors.163.com'
W: Failed to fetch http://mirrors.163.com/ubuntu/dists/focal-security/InRelease  Temporary failure resolving 'mirrors.163.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cron
E: Unable to locate package openssl
E: Unable to locate package git
E: Unable to locate package wget
E: Unable to locate package tzdata
The command '/bin/sh -c date && apt-get update && apt-get install -y cron openssl coreutils git wget tzdata          && apt-get update && apt-get install -y python3 python3-pip' returned a non-zero code: 100
ERROR: Service 'xmly1' failed to build


这里就有点奇怪，直接 ping mirrors.aliyun.com、mirrors.163.com是可以 ping 通的，但是docker命令哪里却无法拉取，烦请看看是哪里的问题，非常感谢

Docker version 20.10.2, build 2291f61
docker-compose version 1.28.2, build 67630359
pip 21.0.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)
docker-py version: 4.4.1
CPython version: 3.6.9
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

**Comment by Nothend** [comment]
顺便说下，我的openwrt 是运行在x86虚拟机esxi 下的（编译自lean的代码）

**Comment by Darkatse** [comment]
看起来是docker里面dns解析出了问题，你可以试一下把docker-compose.yml第一行的版本改成2.2，然后改动build块中的内容为
```
build:
  context: .  
  network: host  
  dockerfile: ./Dockerfile
```
再重新启动尝试

**Comment by Darkatse** [comment]
如果还是不行就编辑一下 /etc/docker/daemon.json 文件，如果没有的话就新建一个，然后添加下面的内容
```
{
    "dns": ["114.114.114.114", "1.0.0.1"]
}
```
使得docker里指向正确的DNS地址，当然有的话你可以填入自己的内网DNS地址

**Comment by Nothend** [comment]
> 如果还是不行就编辑一下 /etc/docker/daemon.json 文件，如果没有的话就新建一个，然后添加下面的内容
> 
> ```
> {
>     "dns": ["114.114.114.114", "1.0.0.1"]
> }
> ```
> 
> 使得docker里指向正确的DNS地址，当然有的话你可以填入自己的内网DNS地址

非常感谢，按照你的办法成功了！
